### PR TITLE
Fix build on other Linux architectures

### PR DESCRIPTION
**Pull request by yselkowitz**
Merge from upstream:

https://github.com/kubernetes-sigs/kubefed/pull/1039
https://github.com/kubernetes-sigs/kubefed/commit/6370d758172836c6501fe33764f0c9f6e37aa3bb

We will need this in 4.2 and later branches.

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
@yselkowitz Thanks for filing this PR. It looks like we're planning to fast-forward our master branch to upstream `v0.1.0-rc4` release which includes your change as well so I'm closing this PR to avoid any duplicate work.

**Comment by yselkowitz** [comment]
@sohankunkerkar will 4.2 and 4.3 branches also be fast-forwarded?  We need those fixed as well.

**Comment by abhat** [comment]
@yselkowitz yes, those will get forwarded from the downstream master.

**Pull request closed without merging**
